export const data = [
  { name: "Sold", color: "#BD1FBE", value: 62 },
  { name: "Got free", color: "#FC64FF", value: 233 },
  { name: "Sold", color: "#BD1FBE", value: 145 },
  { name: "Burned", color: "#1be63b", value: 263 },
  { name: "Free float", color: "#99a4b2", value: 20 },
  { name: "Sold", color: "#BD1FBE", value: 547 },
  { name: "Sold", color: "#BD1FBE", value: 177 },
  { name: "Got free", color: "#FC64FF", value: 143 },
  { name: "Got free", color: "#FC64FF", value: 181 },
  { name: "Burned", color: "#1be63b", value: 433 },
  { name: "Got free", color: "#FC64FF", value: 340 },
  { name: "Free float", color: "#99a4b2", value: 543 },
  { name: "Free float", color: "#99a4b2", value: 85 },
  { name: "Free float", color: "#99a4b2", value: 124 },
  { name: "Got free", color: "#FC64FF", value: 954 },
  { name: "Burned", color: "#1be63b", value: 51 },
  { name: "Free float", color: "#99a4b2", value: 123 },
  { name: "Sold", color: "#BD1FBE", value: 654 },
  { name: "Burned", color: "#1be63b", value: 123 },
  { name: "Free float", color: "#99a4b2", value: 54 },
  { name: "Sold", color: "#BD1FBE", value: 1 },
  { name: "Sold", color: "#BD1FBE", value: 0 },
  { name: "Burned", color: "#1be63b", value: 52 },
  { name: "Got free", color: "#FC64FF", value: 243 },
  { name: "Got free", color: "#FC64FF", value: 323 },
  { name: "Got free", color: "#FC64FF", value: 601 },
  { name: "Free float", color: "#99a4b2", value: 99 },
  { name: "Free float", color: "#99a4b2", value: 34 },
  { name: "Free float", color: "#99a4b2", value: 309 },
  { name: "Got free", color: "#FC64FF", value: 138 },
  { name: "Free float", color: "#99a4b2", value: 80 },
  { name: "Sold", color: "#BD1FBE", value: 189 },
  { name: "Burned", color: "#1be63b", value: 563 },
  { name: "Free float", color: "#99a4b2", value: 401 },
  { name: "Sold", color: "#BD1FBE", value: 310 },
  { name: "Sold", color: "#BD1FBE", value: 205 },
  { name: "Got free", color: "#FC64FF", value: 105 },
  { name: "Got free", color: "#FC64FF", value: 100 },
  { name: "Burned", color: "#1be63b", value: 303 },
  { name: "Got free", color: "#FC64FF", value: 90 },
  { name: "Free float", color: "#99a4b2", value: 210 },
  { name: "Free float", color: "#99a4b2", value: 437 },
  { name: "Burned", color: "#1be63b", value: 163 },
  { name: "Free float", color: "#99a4b2", value: 581 },
  { name: "Got free", color: "#FC64FF", value: 119 },
  { name: "Free float", color: "#99a4b2", value: 234 },
  { name: "Got free", color: "#FC64FF", value: 90 },
  { name: "Free float", color: "#99a4b2", value: 210 },
  { name: "Free float", color: "#99a4b2", value: 437 },
  { name: "Burned", color: "#1be63b", value: 163 },
  { name: "Free float", color: "#99a4b2", value: 581 },
  { name: "Sold", color: "#BD1FBE", value: 189 },
  { name: "Burned", color: "#1be63b", value: 563 },
  { name: "Free float", color: "#99a4b2", value: 401 },
];

export const legend = [
  {
    id: 0,
    name: "Sold",
    color: "#BD1FBE",
  },
  {
    id: 1,
    name: "Got free",
    color: "#FC64FF",
  },
  {
    id: 2,
    name: "Burned",
    color: "#1be63b",
  },
  {
    id: 3,
    name: "Free float",
    color: "#99a4b2",
  },
];
